In [30]:
import pandas as pd
import numpy as np
import os

# os.chdir("/content/gdrive/MyDrive/AML_FINAL")
# retval = os.getcwd()
# retval


'/content/gdrive/MyDrive/AML_FINAL'

In [31]:
usr_comments_emb_test=pd.read_csv("users_comments_emb_test.csv")

In [32]:
usr_comments_emb_test = usr_comments_emb_test.fillna(value=0)
usr_comments_emb_test.head(10)

Postid  commentnumber_0_"comment text cluster_0  \
0  5lj7sy                                      0.0   
1  5lkwas                                      0.0   
2  5luwog                                      0.0   
3  5m2nvj                                      0.0   
4  5m17rk                                      0.0   
5  5mhx8w                                      0.0   
6  5mjdc2                                      0.0   
7  5mvubh                                      0.0   
8  5n956u                                      0.0   
9  5nmf5e                                      0.0   

   commentnumber_0_"comment text cluster_1  \
0                                      0.0   
1                                      0.0   
2                                      0.0   
3                                      0.0   
4                                      1.0   
5                                      0.0   
6                                      0.0   
7                                      0.0   
8                                      0.0   
9                                      0.0   

   commentnumber_0_"comment text cluster_2  \
0                                      0.0   
1                                      0.0   
2                                      0.0   
3                                      0.0   
4                                      0.0   
5                                      1.0   
6                                      0.0   
7                                      1.0   
8                                      1.0   
9                                      0.0   

   commentnumber_0_"comment text cluster_3  \
0                                      0.0   
1                                      0.0   
2                                      0.0   
3                                      1.0   
4                                      0.0   
5                                      0.0   
6                                      0.0   
7                                      0.0   
8                                      0.0   
9                                      0.0   

   commentnumber_0_"comment text cluster_4  \
0                                      1.0   
1                                      1.0   
2                                      0.0   
3                                      0.0   
4                                      0.0   
5                                      0.0   
6                                      1.0   
7                                      0.0   
8                                      0.0   
9                                      1.0   

   commentnumber_0_"comment text cluster_5  \
0                                      0.0   
1                                      0.0   
2                                      1.0   
3                                      0.0   
4                                      0.0   
5                                      0.0   
6                                      0.0   
7                                      0.0   
8                                      0.0   
9                                      0.0   

   commentnumber_1_"comment text cluster_0  \
0                                      0.0   
1                                      0.0   
2                                      0.0   
3                                      1.0   
4                                      0.0   
5                                      0.0   
6                                      0.0   
7                                      0.0   
8                                      0.0   
9                                      0.0   

   commentnumber_1_"comment text cluster_1  \
0                                      0.0   
1                                      0.0   
2                                      0.0   
3                                      0.0   
4                                      0.0   
5                                      0.0   
6                                      0.0  

In [33]:
usr_comments_emb_train=pd.read_csv("usre's_comments_emb_train.csv")
# usr_comments_emb_train.head(20)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (0,11730) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [34]:
usr_comments_emb_train = usr_comments_emb_train.fillna(value=0)
usr_comments_emb_train.head(10)

Postid  commentnumber_0_"comment text cluster_0  \
0  5lezhz                                      0.0   
1  5lge1y                                      0.0   
2  5lspep                                      0.0   
3  5luwz3                                      0.0   
4  5lxfq0                                      0.0   
5  5m3iwd                                      0.0   
6  5m5ue0                                      0.0   
7  5m9b71                                      1.0   
8  5m94pt                                      0.0   
9  5mau6z                                      0.0   

   commentnumber_0_"comment text cluster_1  \
0                                      0.0   
1                                      1.0   
2                                      1.0   
3                                      1.0   
4                                      1.0   
5                                      0.0   
6                                      1.0   
7                                      0.0   
8                                      1.0   
9                                      1.0   

   commentnumber_0_"comment text cluster_2  \
0                                      1.0   
1                                      0.0   
2                                      0.0   
3                                      0.0   
4                                      0.0   
5                                      0.0   
6                                      0.0   
7                                      0.0   
8                                      0.0   
9                                      0.0   

   commentnumber_0_"comment text cluster_3  \
0                                      0.0   
1                                      0.0   
2                                      0.0   
3                                      0.0   
4                                      0.0   
5                                      1.0   
6                                      0.0   
7                                      0.0   
8                                      0.0   
9                                      0.0   

   commentnumber_0_"comment text cluster_4  \
0                                      0.0   
1                                      0.0   
2                                      0.0   
3                                      0.0   
4                                      0.0   
5                                      0.0   
6                                      0.0   
7                                      0.0   
8                                      0.0   
9                                      0.0   

   commentnumber_0_"comment text cluster_5  \
0                                      0.0   
1                                      0.0   
2                                      0.0   
3                                      0.0   
4                                      0.0   
5                                      0.0   
6                                      0.0   
7                                      0.0   
8                                      0.0   
9                                      0.0   

   commentnumber_1_"comment text cluster_0  \
0                                      0.0   
1                                      0.0   
2                                      0.0   
3                                      0.0   
4                                      0.0   
5                                      0.0   
6                                      0.0   
7                                      0.0   
8                                      0.0   
9                                      0.0   

   commentnumber_1_"comment text cluster_1  \
0                                      1.0   
1                                      1.0   
2                                      1.0   
3                                      0.0   
4                                      0.0   
5                                      0.0   
6                                      1.0  

In [1]:
! git clone https://github.com/elana1fel/Dreaddit_implementation.git

Cloning into 'Dreaddit_implementation'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 1), reused 6 (delta 1), pack-reused 0
Unpacking objects: 100% (11/11), done.


In [12]:
import os
os.chdir("/content/Dreaddit_implementation")
main_path = os.getcwd()
main_path

'/content/Dreaddit_implementation'

In [16]:
import pandas as pd
import numpy as np
import os
os.chdir("/content/Dreaddit_implementation")
main_path = os.getcwd()
main_path


train = pd.read_csv("dreaddit-train.csv")
test = pd.read_csv("dreaddit-test.csv")

import os
os.chdir("/content/Dreaddit_implementation/user_comments_embeddings")
main_path = os.getcwd()
main_path

usr_comments_emb_train=pd.read_csv("users_comments_emb_train.csv")
usr_comments_emb_test=pd.read_csv("users_comments_emb_test.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (0,11730) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [17]:
def add_domain(df):
    df['domain'] = df['subreddit'].map(
        {
        'domesticviolence':'abuse',
        'survivorsofabuse':'abuse',
        'anxiety':'anxiety',
        'stress':'anxiety',
        'almosthomeless':'financial',
        'assistance':'financial',
        'food_pantry':'financial',
        'homeless':'financial',
        'ptsd':'ptsd',
        'relationships':'social',
        }
    )
    return df

In [18]:
train = add_domain(train)
test = add_domain(test)

In [19]:
train['Postid']=train['post_id']
test['Postid']=test['post_id']


In [20]:
train.head(2)

subreddit post_id sentence_range  \
0        ptsd  8601tu       (15, 20)   
1  assistance  8lbrx9         (0, 5)   

                                                text     id  label  \
0  He said he had not felt that way before, sugge...  33181      1   
1  Hey there r/assistance, Not sure if this is th...   2606      0   

   confidence  social_timestamp  social_karma  syntax_ari  ...  \
0         0.8        1521614353             5    1.806818  ...   
1         1.0        1527009817             4    9.429737  ...   

   lex_dal_min_imagery  lex_dal_avg_activation  lex_dal_avg_imagery  \
0                  1.0                 1.77000              1.52211   
1                  1.0                 1.69586              1.62045   

   lex_dal_avg_pleasantness  social_upvote_ratio  social_num_comments  \
0                   1.89556                 0.86                    1   
1                   1.88919                 0.65                    2   

   syntax_fk_grade  sentiment     domain  Postid  
0         3.253573  -0.002742       ptsd  8601tu  
1         8.828316   0.292857  financial  8lbrx9  

[2 rows x 118 columns]

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train['subreddit_new'] = le.fit_transform(train['subreddit'])
train['domain_new'] = le.fit_transform(train['domain'])

test['subreddit_new'] = le.fit_transform(test['subreddit'])
test['domain_new'] = le.fit_transform(test['domain'])


In [30]:
usr_comments_emb_train.head(2)

commentnumber_0_"comment text cluster_0  \
Postid                                            
5lezhz                                      0.0   
5lge1y                                      0.0   

        commentnumber_0_"comment text cluster_1  \
Postid                                            
5lezhz                                      0.0   
5lge1y                                      1.0   

        commentnumber_0_"comment text cluster_2  \
Postid                                            
5lezhz                                      1.0   
5lge1y                                      0.0   

        commentnumber_0_"comment text cluster_3  \
Postid                                            
5lezhz                                      0.0   
5lge1y                                      0.0   

        commentnumber_0_"comment text cluster_4  \
Postid                                            
5lezhz                                      0.0   
5lge1y                                      0.0   

        commentnumber_0_"comment text cluster_5  \
Postid                                            
5lezhz                                      0.0   
5lge1y                                      0.0   

        commentnumber_1_"comment text cluster_0  \
Postid                                            
5lezhz                                      0.0   
5lge1y                                      0.0   

        commentnumber_1_"comment text cluster_1  \
Postid                                            
5lezhz                                      1.0   
5lge1y                                      1.0   

        commentnumber_1_"comment text cluster_2  \
Postid                                            
5lezhz                                      0.0   
5lge1y                                      0.0   

        commentnumber_1_"comment text cluster_3  ...  \
Postid                                           ...   
5lezhz                                      0.0  ...   
5lge1y                                      0.0  ...   

        comment_number_128_ AuthorPatreonFlair_1  \
Postid                                             
5lezhz                                       NaN   
5lge1y                                       NaN   

        comment_number_30_ Url (group)_1  comment_number_44_ Url (group)_1  \
Postid                                                                       
5lezhz                               NaN                               NaN   
5lge1y                               NaN                               NaN   

        comment_number_46_ Url (group)_1  comment_number_47_ Url (group)_1  \
Postid                                                                       
5lezhz                               NaN                               NaN   
5lge1y                               NaN                               NaN   

        comment_number_49_ Url (group)_1  comment_number_36_ CanGild_1  \
Postid                                                                   
5lezhz                               NaN                           NaN   
5lge1y                               NaN                           NaN   

        comment_number_38_ CanGild_1  comment_number_37_ CanGild_1  \
Postid                                                               
5lezhz                           NaN                           NaN   
5lge1y                           NaN                           NaN   

        comment_number_65_ CanGild_1  
Postid                                
5lezhz                           NaN  
5lge1y                           NaN  

[2 rows x 13135 columns]

In [31]:
usr_comments_emb_test.head(2)

commentnumber_0_"comment text cluster_0  \
Postid                                            
5lj7sy                                      NaN   
5lkwas                                      NaN   

        commentnumber_0_"comment text cluster_1  \
Postid                                            
5lj7sy                                      NaN   
5lkwas                                      NaN   

        commentnumber_0_"comment text cluster_2  \
Postid                                            
5lj7sy                                      NaN   
5lkwas                                      NaN   

        commentnumber_0_"comment text cluster_3  \
Postid                                            
5lj7sy                                      NaN   
5lkwas                                      NaN   

        commentnumber_0_"comment text cluster_4  \
Postid                                            
5lj7sy                                      1.0   
5lkwas                                      1.0   

        commentnumber_0_"comment text cluster_5  \
Postid                                            
5lj7sy                                      NaN   
5lkwas                                      NaN   

        commentnumber_1_"comment text cluster_0  \
Postid                                            
5lj7sy                                      NaN   
5lkwas                                      NaN   

        commentnumber_1_"comment text cluster_1  \
Postid                                            
5lj7sy                                      NaN   
5lkwas                                      NaN   

        commentnumber_1_"comment text cluster_2  \
Postid                                            
5lj7sy                                      NaN   
5lkwas                                      NaN   

        commentnumber_1_"comment text cluster_3  ...  \
Postid                                           ...   
5lj7sy                                      NaN  ...   
5lkwas                                      NaN  ...   

        comment_number_65_ CanGild_2  comment_number_66_ CanGild_2  \
Postid                                                               
5lj7sy                           NaN                           NaN   
5lkwas                           NaN                           NaN   

        comment_number_67_ CanGild_2  comment_number_68_ CanGild_2  \
Postid                                                               
5lj7sy                           NaN                           NaN   
5lkwas                           NaN                           NaN   

        comment_number_69_ CanGild_2  comment_number_70_ CanGild_2  \
Postid                                                               
5lj7sy                           NaN                           NaN   
5lkwas                           NaN                           NaN   

        comment_number_71_ CanGild_2  comment_number_72_ CanGild_2  \
Postid                                                               
5lj7sy                           NaN                           NaN   
5lkwas                           NaN                           NaN   

        comment_number_73_ CanGild_2  comment_number_126_ CanGild_1  
Postid                                                               
5lj7sy                           NaN                            NaN  
5lkwas                           NaN                            NaN  

[2 rows x 13134 columns]

In [24]:
usr_comments_emb_train=usr_comments_emb_train.set_index('Postid')
train=train.set_index('Postid')

In [25]:
train.head(1)

subreddit post_id sentence_range  \
Postid                                    
8601tu      ptsd  8601tu       (15, 20)   

                                                     text     id  label  \
Postid                                                                    
8601tu  He said he had not felt that way before, sugge...  33181      1   

        confidence  social_timestamp  social_karma  syntax_ari  ...  \
Postid                                                          ...   
8601tu         0.8        1521614353             5    1.806818  ...   

        lex_dal_avg_activation  lex_dal_avg_imagery  lex_dal_avg_pleasantness  \
Postid                                                                          
8601tu                    1.77              1.52211                   1.89556   

        social_upvote_ratio  social_num_comments  syntax_fk_grade  sentiment  \
Postid                                                                         
8601tu                 0.86                    1         3.253573  -0.002742   

        domain  subreddit_new  domain_new  
Postid                                     
8601tu    ptsd              6           3  

[1 rows x 119 columns]

In [26]:
test=test.set_index('Postid')

In [27]:
usr_comments_emb_test=usr_comments_emb_test.set_index('Postid')
usr_comments_emb_train=usr_comments_emb_train.set_index('Postid')

In [32]:
#train data join original train data with user's comments embedding type of join 
temp_train_df=train.join(usr_comments_emb_train, how='left').fillna(value=0)
temp_train_df.head(2)

subreddit post_id sentence_range  \
Postid                                            
5lezhz  domesticviolence  5lezhz       [14, 19]   
5lezhz  domesticviolence  5lezhz        (5, 10)   

                                                     text     id  label  \
Postid                                                                    
5lezhz  He came after me a few times so I got away and...    313      1   
5lezhz  We will get through this and I am determined, ...  31536      1   

        confidence  social_timestamp  social_karma  syntax_ari  ...  \
Postid                                                          ...   
5lezhz    0.571429        1483274218             4    0.531035  ...   
5lezhz    0.857143        1483274218             4    8.679730  ...   

        comment_number_128_ AuthorPatreonFlair_1  \
Postid                                             
5lezhz                                       0.0   
5lezhz                                       0.0   

        comment_number_30_ Url (group)_1  comment_number_44_ Url (group)_1  \
Postid                                                                       
5lezhz                               0.0                               0.0   
5lezhz                               0.0                               0.0   

        comment_number_46_ Url (group)_1  comment_number_47_ Url (group)_1  \
Postid                                                                       
5lezhz                               0.0                               0.0   
5lezhz                               0.0                               0.0   

        comment_number_49_ Url (group)_1  comment_number_36_ CanGild_1  \
Postid                                                                   
5lezhz                               0.0                           0.0   
5lezhz                               0.0                           0.0   

        comment_number_38_ CanGild_1  comment_number_37_ CanGild_1  \
Postid                                                               
5lezhz                           0.0                           0.0   
5lezhz                           0.0                           0.0   

        comment_number_65_ CanGild_1  
Postid                                
5lezhz                           0.0  
5lezhz                           0.0  

[2 rows x 13254 columns]

In [34]:
#test data join original test data with user's comments embedding type of join 
temp_test_df=test.join(usr_comments_emb_test, how='left').fillna(value=0)
temp_test_df.head(2)


id   subreddit post_id sentence_range  \
Postid                                            
5lj7sy   316  assistance  5lj7sy         [2, 7]   
5lkwas  1805     anxiety  5lkwas         [0, 5]   

                                                     text  label  confidence  \
Postid                                                                         
5lj7sy  All the research are being conducted by Harvar...      0         1.0   
5lkwas  Well maybe afraid isn't the best word, but it'...      1         1.0   

        social_timestamp  social_karma  syntax_ari  ...  \
Postid                                              ...   
5lj7sy      1.483330e+09             4    4.790905  ...   
5lkwas      1.483358e+09             5   12.909562  ...   

        comment_number_65_ CanGild_2  comment_number_66_ CanGild_2  \
Postid                                                               
5lj7sy                           0.0                           0.0   
5lkwas                           0.0                           0.0   

        comment_number_67_ CanGild_2  comment_number_68_ CanGild_2  \
Postid                                                               
5lj7sy                           0.0                           0.0   
5lkwas                           0.0                           0.0   

        comment_number_69_ CanGild_2  comment_number_70_ CanGild_2  \
Postid                                                               
5lj7sy                           0.0                           0.0   
5lkwas                           0.0                           0.0   

        comment_number_71_ CanGild_2  comment_number_72_ CanGild_2  \
Postid                                                               
5lj7sy                           0.0                           0.0   
5lkwas                           0.0                           0.0   

        comment_number_73_ CanGild_2  comment_number_126_ CanGild_1  
Postid                                                               
5lj7sy                           0.0                            0.0  
5lkwas                           0.0                            0.0  

[2 rows x 13253 columns]

In [35]:
y_train = temp_train_df['label']
y_test = temp_test_df['label']
X_train = temp_train_df.drop([ 'sentence_range', 'id','domain','subreddit','text','label','Postid.1'], axis = 1)
X_test=temp_test_df.drop([ 'sentence_range', 'id','domain','subreddit','text','label'], axis = 1)

In [36]:
# X_train

In [37]:

# Select only original info feature columns only  no text of the post and the comments clustering features
X1_train = X_train.iloc[: , :1509]
X1_test = X_test.iloc[: , :544]
X1_test['IND']='test'
X1_train['IND']='train'
# X1_train

In [38]:
XX = pd.concat([X1_train, X1_test], axis=0).fillna(value=0)
# df1 = df[df['Age'] >= 37]
X1_train=XX[XX['IND'] == 'train']
X1_test=XX[XX['IND'] == 'test']
X1_test

post_id  confidence  social_timestamp  social_karma  syntax_ari  \
Postid                                                                   
5lj7sy  5lj7sy    1.000000      1.483330e+09             4    4.790905   
5lkwas  5lkwas    1.000000      1.483358e+09             5   12.909562   
5luwog  5luwog    1.000000      1.483482e+09            20    7.035387   
5luwog  5luwog    1.000000      1.483482e+09            20    4.428108   
5m17rk  5m17rk    0.800000      1.483558e+09             5    7.303286   
...        ...         ...               ...           ...         ...   
9y3go5  9y3go5    1.000000      1.542518e+09             5   -1.347516   
9y7u1a  9y7u1a    0.000000      1.542562e+09             3    5.869032   
9y9zn9  9y9zn9    0.833333      1.542576e+09            10    3.382097   
9yac89  9yac89    0.600000      1.542579e+09            32    6.409853   
9yayit  9yayit    0.600000      1.542583e+09             3    5.306056   

        lex_liwc_WC  lex_liwc_Analytic  lex_liwc_Clout  lex_liwc_Authentic  \
Postid                                                                       
5lj7sy           69              95.25           71.89               27.39   
5lkwas          150               5.16           10.28               76.49   
5luwog          120              41.99            7.84               88.91   
5luwog           68              22.92            1.00               99.00   
5m17rk           69              92.84           95.89               13.90   
...             ...                ...             ...                 ...   
9y3go5           63               6.90           56.31               27.77   
9y7u1a           90              20.13           71.09               65.14   
9y9zn9           61              43.04           74.41                3.16   
9yac89          112              67.14            6.47               98.92   
9yayit           70              13.85            1.00               99.00   

        lex_liwc_Tone  ...  commentnumber_88_"comment text cluster_5  \
Postid                 ...                                             
5lj7sy          98.72  ...                                       0.0   
5lkwas           2.41  ...                                       0.0   
5luwog           1.00  ...                                       0.0   
5luwog           1.76  ...                                       0.0   
5m17rk          78.80  ...                                       0.0   
...               ...  ...                                       ...   
9y3go5           7.46  ...                                       0.0   
9y7u1a          46.22  ...                                       0.0   
9y9zn9          83.88  ...                                       0.0   
9yac89           1.00  ...                                       0.0   
9yayit           8.64  ...                                       0.0   

        commentnumber_89_"comment text cluster_5  \
Postid                                             
5lj7sy                                       0.0   
5lkwas                                       0.0   
5luwog                                       0.0   
5luwog                                       0.0   
5m17rk                                       0.0   
...                                          ...   
9y3go5                                       0.0   
9y7u1a                                       0.0   
9y9zn9                                       0.0   
9yac89                                       0.0   
9yayit                                       0.0   

        commentnumber_92_"comment text cluster_5  \
Postid                                             
5lj7sy                                       0.0   
5lkwas                                       0.0   
5luwog                                       0.0   
5luwog                                       0.0   
5m17rk                                       0.0   
...                                          ...   

# **Utils functions**


In [39]:
# import warnings filter
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

In [40]:
summ_results=[]
y_pred_summ = []

In [42]:
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score
from sklearn import model_selection
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report


# evaluate a given model using cross-validation
def evaluate_model(y_test, y_pred):
	results = classification_report(y_pred, y_test, output_dict=True)
	conf_mat = confusion_matrix(y_test, y_pred)
	scores = { 'precision':results['weighted avg']['precision'],\
             'recall':results['weighted avg']['recall'],\
             'f1_score':results['weighted avg']['f1-score'],\
             'confusion_matrix': conf_mat}

	return scores


In [43]:
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, AdaBoostClassifier

from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

import warnings
warnings.filterwarnings(action='ignore', category=UserWarning)
def get_models(models_to_drop=None):
    models = dict()
    models['lr'] = make_pipeline(StandardScaler(), LogisticRegression(solver = 'saga', C = 70.0))
    models['knn'] = make_pipeline(StandardScaler(), KNeighborsClassifier())
    models['DecisionTree'] = DecisionTreeClassifier(max_depth = 1)
    models['svm'] = make_pipeline(StandardScaler(), SVC())
    models['bayes'] = make_pipeline(StandardScaler(), GaussianNB())
    models['xgboost'] = XGBClassifier(n_estimators = 11, max_depth = 1)
    models['GBM'] = GradientBoostingClassifier(n_estimators = 10)
    models['rf'] = RandomForestClassifier(n_estimators = 10)
    models['adaboost'] = AdaBoostClassifier(n_estimators= 12)

    if models_to_drop is not None:
      for model in models_to_drop:
        del models[model]
    return models

In [44]:
def create_res(scores, name, method):
  if method is None:
    method_name = name
  else:
    method_name = method + '_' + name
  res = {'name':method_name,\
         'precision':scores['precision'],\
         'recall':scores['recall'],\
         'f1':scores['f1_score'],\
         'confusion_matrix': scores['confusion_matrix']}
  return res

In [45]:
def get_eval():
	# get the models to evaluate
	models = get_models()
	# evaluate the models and store results
	results, names = list(), list()
	for name, model in models.items():
		model.fit(x_train, y_train)
		y_pred = model.predict(x_test)
		scores = evaluate_model(y_test, y_pred)
		results.append(scores)
		names.append(name)

		print(f"{name} : precision: {scores['precision']:.2f}, recall: {scores['recall']:.2f}, f1_score: {scores['f1_score']:.2f}")
		print(f" confusion_matrix: \n {scores['confusion_matrix']}")
		res = create_res(scores, name, method)
		summ_results.append(res)
		y_pred_summ.append({'name': res['name'], 'y_pred': y_pred})

In [46]:
from sklearn.ensemble import VotingClassifier
from joblib import parallel_backend

def get_majority_vote():
  models_dict = get_models()
  models = []
  for key in models_dict.keys():
    models.append((key, models_dict[key]))

  majority = VotingClassifier(estimators=models,
                              n_jobs=-1,
                              voting='hard',
                              verbose=True)
  with parallel_backend('threading', n_jobs=6):
      majority.fit(x_train, y_train)
  majority_pred = majority.predict(x_test)

  from sklearn.metrics import confusion_matrix, classification_report
  majority_res = classification_report(y_test, majority_pred, output_dict=True)
  confusion_res = confusion_matrix(y_test, majority_pred)
  scores = { 'precision':majority_res['weighted avg']['precision'],\
             'recall':majority_res['weighted avg']['recall'],\
             'f1_score':majority_res['weighted avg']['f1-score'],\
             'confusion_matrix': confusion_res}
  print(majority_res)
  summ_results.append(create_res(scores, 'majority vote', method))

In [47]:
def get_majority_vote_correlated(y_pred_df):
  corr = y_pred_df.corr().abs()

  # Select upper triangle of correlation matrix
  upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(np.bool))

  # Find index of feature columns with correlation greater than 0.8
  to_drop = [column for column in upper.columns if any(upper[column] > 0.8)]
  print(f"droping: {to_drop}")
  if len(to_drop)<1:
      to_drop = [column for column in upper.columns if any(upper[column] > 0.7)]
      if len(to_drop)<1:
        return
      print(f"droping: {to_drop}")

  models_dict = get_models(to_drop)
  models = []
  for key in models_dict.keys():
    models.append((key, models_dict[key]))

  majority = VotingClassifier(estimators=models,
                              n_jobs=-1,
                              voting='hard',
                              verbose=True)
  with parallel_backend('threading', n_jobs=6):
      majority.fit(x_train, y_train)
  majority_pred = majority.predict(x_test)

  from sklearn.metrics import confusion_matrix, classification_report
  majority_res = classification_report(y_test, majority_pred, output_dict=True)
  confusion_res = confusion_matrix(y_test, majority_pred)
  scores = { 'precision':majority_res['weighted avg']['precision'],\
             'recall':majority_res['weighted avg']['recall'],\
             'f1_score':majority_res['weighted avg']['f1-score'],\
             'confusion_matrix': confusion_res}

  print(majority_res)
  summ_results.append(create_res(scores, 'majority vote', method))

In [48]:
method = 'Orig_features_no_post_comments_usr_emb_text_cluster'
#not using post original text at all,only original features features and the clusters of the comments to the post based on word2vec comments embeding

In [52]:

X1_train=X1_train.drop(['IND'], axis = 1)
X1_test=X1_test.drop(['IND'], axis = 1)
x_train = X1_train
x_test = X1_test
x_train = x_train.drop(['post_id'], axis = 1)
x_test=x_test.drop([ 'post_id'], axis = 1)
get_eval()

lr : precision: 0.74, recall: 0.74, f1_score: 0.74
 confusion_matrix: 
 [[258  88]
 [101 268]]
knn : precision: 0.66, recall: 0.64, f1_score: 0.64
 confusion_matrix: 
 [[178 168]
 [ 92 277]]
DecisionTree : precision: 0.76, recall: 0.73, f1_score: 0.74
 confusion_matrix: 
 [[207 139]
 [ 54 315]]
svm : precision: 0.72, recall: 0.72, f1_score: 0.72
 confusion_matrix: 
 [[260  86]
 [113 256]]
bayes : precision: 0.87, recall: 0.52, f1_score: 0.63
 confusion_matrix: 
 [[ 27 319]
 [ 26 343]]
xgboost : precision: 0.75, recall: 0.74, f1_score: 0.74
 confusion_matrix: 
 [[228 118]
 [ 69 300]]
GBM : precision: 0.77, recall: 0.73, f1_score: 0.74
 confusion_matrix: 
 [[202 144]
 [ 47 322]]
rf : precision: 0.71, recall: 0.71, f1_score: 0.71
 confusion_matrix: 
 [[246 100]
 [105 264]]
adaboost : precision: 0.72, recall: 0.69, f1_score: 0.70
 confusion_matrix: 
 [[198 148]
 [ 71 298]]


In [54]:
get_majority_vote()

[Voting] ............. (3 of 9) Processing DecisionTree, total=   0.1s
[Voting] ...................... (2 of 9) Processing knn, total=   0.2s
[Voting] .................... (5 of 9) Processing bayes, total=   0.2s
[Voting] .................. (6 of 9) Processing xgboost, total=   1.4s
[Voting] ...................... (7 of 9) Processing GBM, total=   1.5s
[Voting] ....................... (8 of 9) Processing rf, total=   0.3s
[Voting] ................. (9 of 9) Processing adaboost, total=   0.9s
[Voting] ....................... (1 of 9) Processing lr, total=   5.5s
[Voting] ...................... (4 of 9) Processing svm, total=   5.8s
{'0': {'precision': 0.7747440273037542, 'recall': 0.6560693641618497, 'f1-score': 0.7104851330203442, 'support': 346}, '1': {'precision': 0.7180094786729858, 'recall': 0.8211382113821138, 'f1-score': 0.7661188369152971, 'support': 369}, 'accuracy': 0.7412587412587412, 'macro avg': {'precision': 0.74637675298837, 'recall': 0.7386037877719818, 'f1-score': 0.738

In [56]:
def get_res_for_corr():
  results_for_corr = [{i['name'].split(method + '_')[1]: i['y_pred']} for i in y_pred_summ if method in i['name']]
  results_for_corr = dict((key, val) for k in results_for_corr for key, val in k.items())
  results_for_corr_df = pd.DataFrame.from_dict(results_for_corr)
  return results_for_corr_df

In [57]:
results_for_corr_df = get_res_for_corr()
method = method + '_correlated'

get_majority_vote_correlated(results_for_corr_df)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


droping: ['svm']
[Voting] ............. (3 of 8) Processing DecisionTree, total=   0.1s
[Voting] ...................... (2 of 8) Processing knn, total=   0.2s
[Voting] .................... (4 of 8) Processing bayes, total=   0.2s
[Voting] ....................... (7 of 8) Processing rf, total=   0.2s
[Voting] .................. (5 of 8) Processing xgboost, total=   0.8s
[Voting] ................. (8 of 8) Processing adaboost, total=   0.8s
[Voting] ...................... (6 of 8) Processing GBM, total=   1.3s
[Voting] ....................... (1 of 8) Processing lr, total=   4.6s
{'0': {'precision': 0.7785234899328859, 'recall': 0.6705202312138728, 'f1-score': 0.7204968944099378, 'support': 346}, '1': {'precision': 0.7266187050359713, 'recall': 0.8211382113821138, 'f1-score': 0.7709923664122138, 'support': 369}, 'accuracy': 0.7482517482517482, 'macro avg': {'precision': 0.7525710974844286, 'recall': 0.7458292212979933, 'f1-score': 0.7457446304110757, 'support': 715}, 'weighted avg': {'pr

In [58]:
import gensim

In [59]:
# method = 'Word2vec' to original post
tokenize=train['text'].apply(lambda x: x.split())
w2vec_model=gensim.models.Word2Vec(tokenize,min_count = 1, size = 500, window = 5, sg = 1)
w2vec_model.train(tokenize,total_examples= len(train['text']),epochs=20)

(3745496, 4862620)

In [60]:
w2v_words = list(w2vec_model.wv.vocab)

In [61]:
vector=[]
from tqdm import tqdm
for sent in tqdm(tokenize):
  sent_vec=np.zeros(500)
  count =0
  for word in sent: 
    if word in w2v_words:
      vec = w2vec_model.wv[word]
      sent_vec += vec 
      count += 1
  if count != 0:
    sent_vec /= count #normalize
  vector.append(sent_vec)
print(len(vector))
print(len(vector[0]))

100%|██████████| 2838/2838 [00:10<00:00, 275.07it/s]

2838
500


In [64]:
#embeding word2vec for the original post in train
w2v_train=pd.DataFrame(vector)
w2v_train.head(2)

0         1         2         3         4         5         6    \
0 -0.034612  0.062181  0.084432 -0.005154  0.003201 -0.060175  0.089751   
1 -0.022602  0.099563  0.017669  0.039188  0.018872 -0.061612  0.006540   

        7         8         9    ...       490       491       492       493  \
0 -0.038908  0.030649 -0.090670  ... -0.058662  0.015793 -0.023553 -0.125431   
1 -0.036365  0.077193 -0.013396  ... -0.097157  0.061371 -0.028336 -0.120263   

        494       495       496       497       498       499  
0 -0.016372 -0.018425 -0.018268  0.066104 -0.062199 -0.095881  
1  0.030786 -0.043632  0.005000 -0.001712 -0.116033 -0.091316  

[2 rows x 500 columns]

In [65]:

tokenize=test['text'].apply(lambda x: x.split())
w2vec_model=gensim.models.Word2Vec(tokenize,min_count = 1, size = 500, window = 5, sg = 1)
w2vec_model.train(tokenize,total_examples= len(test['text']),epochs=20)

(941225, 1221920)

In [66]:
w2v_words = list(w2vec_model.wv.vocab)

In [67]:
vector=[]
from tqdm import tqdm
for sent in tqdm(tokenize):
  sent_vec=np.zeros(500)
  count =0
  for word in sent: 
    if word in w2v_words:
      vec = w2vec_model.wv[word]
      sent_vec += vec 
      count += 1
  if count != 0:
    sent_vec /= count #normalize
  vector.append(sent_vec)
print(len(vector))
print(len(vector[0]))

100%|██████████| 715/715 [00:01<00:00, 478.80it/s]

715
500


In [68]:
w2v_test=pd.DataFrame(vector)
w2v_test.head(2)

0         1         2         3         4         5         6    \
0  0.006293  0.028790  0.041263 -0.061951  0.034479  0.025510 -0.012009   
1  0.000569  0.028463  0.049625 -0.094096  0.004879 -0.031506 -0.021871   

        7         8         9    ...       490       491       492       493  \
0 -0.032304 -0.011383 -0.046526  ...  0.050090  0.071494 -0.103789 -0.150686   
1 -0.012746 -0.012824 -0.036773  ... -0.010721  0.011800 -0.036532 -0.179604   

        494       495       496       497       498       499  
0 -0.084014  0.026814 -0.046552 -0.004373 -0.104643 -0.111855  
1 -0.069422  0.019358 -0.010319  0.049575 -0.078681 -0.026150  

[2 rows x 500 columns]

In [70]:
#extracting only comments clustering embeding for train data
clusters_train=X1_train.iloc[:,113:].reset_index()
clusters_train=clusters_train.drop(['Postid'], axis = 1)
clusters_train.head(2)

commentnumber_0_"comment text cluster_0  \
0                                      0.0   
1                                      0.0   

   commentnumber_0_"comment text cluster_1  \
0                                      0.0   
1                                      0.0   

   commentnumber_0_"comment text cluster_2  \
0                                      1.0   
1                                      1.0   

   commentnumber_0_"comment text cluster_3  \
0                                      0.0   
1                                      0.0   

   commentnumber_0_"comment text cluster_4  \
0                                      0.0   
1                                      0.0   

   commentnumber_0_"comment text cluster_5  \
0                                      0.0   
1                                      0.0   

   commentnumber_1_"comment text cluster_0  \
0                                      0.0   
1                                      0.0   

   commentnumber_1_"comment text cluster_1  \
0                                      1.0   
1                                      1.0   

   commentnumber_1_"comment text cluster_2  \
0                                      0.0   
1                                      0.0   

   commentnumber_1_"comment text cluster_3  ...  \
0                                      0.0  ...   
1                                      0.0  ...   

   commentnumber_88_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_89_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_92_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_94_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_96_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_97_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_112_"comment text cluster_5  \
0                                        0.0   
1                                        0.0   

   commentnumber_118_"comment text cluster_5  \
0                                        0.0   
1                                        0.0   

   commentnumber_121_"comment text cluster_5  \
0                                        0.0   
1                                        0.0   

   commentnumber_122_"comment text cluster_0  
0                                        0.0  
1                                        0.0  

[2 rows x 1456 columns]

In [71]:
#extracting only comments clustering embeding for test data
clusters_test=X1_test.iloc[:,113:].reset_index()
clusters_test=clusters_test.drop(['Postid'], axis = 1)
clusters_test.head(2)

commentnumber_0_"comment text cluster_0  \
0                                      0.0   
1                                      0.0   

   commentnumber_0_"comment text cluster_1  \
0                                      0.0   
1                                      0.0   

   commentnumber_0_"comment text cluster_2  \
0                                      0.0   
1                                      0.0   

   commentnumber_0_"comment text cluster_3  \
0                                      0.0   
1                                      0.0   

   commentnumber_0_"comment text cluster_4  \
0                                      1.0   
1                                      1.0   

   commentnumber_0_"comment text cluster_5  \
0                                      0.0   
1                                      0.0   

   commentnumber_1_"comment text cluster_0  \
0                                      0.0   
1                                      0.0   

   commentnumber_1_"comment text cluster_1  \
0                                      0.0   
1                                      0.0   

   commentnumber_1_"comment text cluster_2  \
0                                      0.0   
1                                      0.0   

   commentnumber_1_"comment text cluster_3  ...  \
0                                      0.0  ...   
1                                      0.0  ...   

   commentnumber_88_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_89_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_92_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_94_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_96_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_97_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_112_"comment text cluster_5  \
0                                        0.0   
1                                        0.0   

   commentnumber_118_"comment text cluster_5  \
0                                        0.0   
1                                        0.0   

   commentnumber_121_"comment text cluster_5  \
0                                        0.0   
1                                        0.0   

   commentnumber_122_"comment text cluster_0  
0                                        0.0  
1                                        0.0  

[2 rows x 1456 columns]

In [73]:

method = 'Word2vec_for_post_cluster_based_on_word2vec_for comments_text_features'
Xtr = pd.concat([w2v_train, clusters_train], axis=1) 
Xtr.head(2)

0         1         2         3         4         5         6  \
0 -0.034612  0.062181  0.084432 -0.005154  0.003201 -0.060175  0.089751   
1 -0.022602  0.099563  0.017669  0.039188  0.018872 -0.061612  0.006540   

          7         8         9  ...  \
0 -0.038908  0.030649 -0.090670  ...   
1 -0.036365  0.077193 -0.013396  ...   

   commentnumber_88_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_89_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_92_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_94_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_96_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_97_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_112_"comment text cluster_5  \
0                                        0.0   
1                                        0.0   

   commentnumber_118_"comment text cluster_5  \
0                                        0.0   
1                                        0.0   

   commentnumber_121_"comment text cluster_5  \
0                                        0.0   
1                                        0.0   

   commentnumber_122_"comment text cluster_0  
0                                        0.0  
1                                        0.0  

[2 rows x 1956 columns]

In [75]:
Xte = pd.concat([w2v_test, clusters_test], axis=1) 
Xte.head(2)

0         1         2         3         4         5         6  \
0  0.006293  0.028790  0.041263 -0.061951  0.034479  0.025510 -0.012009   
1  0.000569  0.028463  0.049625 -0.094096  0.004879 -0.031506 -0.021871   

          7         8         9  ...  \
0 -0.032304 -0.011383 -0.046526  ...   
1 -0.012746 -0.012824 -0.036773  ...   

   commentnumber_88_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_89_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_92_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_94_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_96_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_97_"comment text cluster_5  \
0                                       0.0   
1                                       0.0   

   commentnumber_112_"comment text cluster_5  \
0                                        0.0   
1                                        0.0   

   commentnumber_118_"comment text cluster_5  \
0                                        0.0   
1                                        0.0   

   commentnumber_121_"comment text cluster_5  \
0                                        0.0   
1                                        0.0   

   commentnumber_122_"comment text cluster_0  
0                                        0.0  
1                                        0.0  

[2 rows x 1956 columns]

In [76]:
#Using only word2vec embeding of the original post and cluster embeding of the comments
x_train = Xtr
x_test = Xte
get_eval()

lr : precision: 0.67, recall: 0.54, f1_score: 0.57
 confusion_matrix: 
 [[ 93 253]
 [ 77 292]]
knn : precision: 0.57, recall: 0.50, f1_score: 0.51
 confusion_matrix: 
 [[237 109]
 [251 118]]
DecisionTree : precision: 0.98, recall: 0.49, f1_score: 0.64
 confusion_matrix: 
 [[343   3]
 [361   8]]
svm : precision: 0.61, recall: 0.56, f1_score: 0.57
 confusion_matrix: 
 [[129 217]
 [101 268]]
bayes : precision: 0.87, recall: 0.52, f1_score: 0.63
 confusion_matrix: 
 [[ 27 319]
 [ 26 343]]
xgboost : precision: 0.96, recall: 0.53, f1_score: 0.67
 confusion_matrix: 
 [[ 12 334]
 [  5 364]]
GBM : precision: 0.80, recall: 0.55, f1_score: 0.62
 confusion_matrix: 
 [[ 59 287]
 [ 38 331]]
rf : precision: 0.50, recall: 0.50, f1_score: 0.50
 confusion_matrix: 
 [[151 195]
 [163 206]]
adaboost : precision: 0.86, recall: 0.52, f1_score: 0.63
 confusion_matrix: 
 [[ 31 315]
 [ 26 343]]


In [77]:
get_majority_vote()

[Voting] ...................... (2 of 9) Processing knn, total=   0.2s
[Voting] ............. (3 of 9) Processing DecisionTree, total=   0.3s
[Voting] .................... (5 of 9) Processing bayes, total=   0.2s
[Voting] .................. (6 of 9) Processing xgboost, total=   1.3s
[Voting] ....................... (8 of 9) Processing rf, total=   0.5s
[Voting] ................. (9 of 9) Processing adaboost, total=   2.9s
[Voting] ...................... (7 of 9) Processing GBM, total=   5.8s
[Voting] ....................... (1 of 9) Processing lr, total=   9.6s
[Voting] ...................... (4 of 9) Processing svm, total=  10.7s
{'0': {'precision': 0.574468085106383, 'recall': 0.23410404624277456, 'f1-score': 0.3326488706365503, 'support': 346}, '1': {'precision': 0.5383275261324042, 'recall': 0.8373983739837398, 'f1-score': 0.655355249204666, 'support': 369}, 'accuracy': 0.5454545454545454, 'macro avg': {'precision': 0.5563978056193937, 'recall': 0.5357512101132572, 'f1-score': 0.49

In [78]:
results_for_corr_df = get_res_for_corr()
method = method + '_correlated'

get_majority_vote_correlated(results_for_corr_df)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


droping: []
droping: ['svm']
[Voting] ...................... (2 of 8) Processing knn, total=   0.2s
[Voting] .................... (4 of 8) Processing bayes, total=   0.2s
[Voting] ............. (3 of 8) Processing DecisionTree, total=   0.3s
[Voting] ....................... (7 of 8) Processing rf, total=   0.5s
[Voting] .................. (5 of 8) Processing xgboost, total=   1.3s
[Voting] ................. (8 of 8) Processing adaboost, total=   2.7s
[Voting] ...................... (6 of 8) Processing GBM, total=   5.6s
[Voting] ....................... (1 of 8) Processing lr, total=   6.3s
{'0': {'precision': 0.5562913907284768, 'recall': 0.24277456647398843, 'f1-score': 0.33802816901408445, 'support': 346}, '1': {'precision': 0.5354609929078015, 'recall': 0.8184281842818428, 'f1-score': 0.647374062165059, 'support': 369}, 'accuracy': 0.5398601398601398, 'macro avg': {'precision': 0.5458761918181392, 'recall': 0.5306013753779156, 'f1-score': 0.49270111558957175, 'support': 715}, 'weigh

In [79]:
X2_train=X_train.reset_index()
Xtr1 = pd.concat([w2v_train, X2_train], axis=1) 
Xtr1['ind']='train'

In [80]:
X2_test=X_test.reset_index()
Xte1 = pd.concat([w2v_test, X2_test], axis=1) 
Xte1['ind']='test'

In [82]:
XXX = pd.concat([Xtr1, Xte1], axis=0).fillna(0)
XXX.head(2)

0         1         2         3         4         5         6  \
0 -0.034612  0.062181  0.084432 -0.005154  0.003201 -0.060175  0.089751   
1 -0.022602  0.099563  0.017669  0.039188  0.018872 -0.061612  0.006540   

          7         8         9  ...  comment_number_30_ Url (group)_1  \
0 -0.038908  0.030649 -0.090670  ...                               0.0   
1 -0.036365  0.077193 -0.013396  ...                               0.0   

   comment_number_44_ Url (group)_1  comment_number_46_ Url (group)_1  \
0                               0.0                               0.0   
1                               0.0                               0.0   

   comment_number_47_ Url (group)_1  comment_number_49_ Url (group)_1  \
0                               0.0                               0.0   
1                               0.0                               0.0   

   comment_number_36_ CanGild_1  comment_number_38_ CanGild_1  \
0                           0.0                           0.0   
1                           0.0                           0.0   

   comment_number_37_ CanGild_1  comment_number_65_ CanGild_1    ind  
0                           0.0                           0.0  train  
1                           0.0                           0.0  train  

[2 rows x 13749 columns]

In [83]:
X22_train=XXX[XXX['ind'] == 'train']
X22_test=XXX[XXX['ind'] == 'test']

In [84]:
method = 'Word2vec_for_post_cluster_based_on_word2vec_for comments_text_features_comments_features'

X22_train = X22_train.drop(['Postid'], axis = 1)
X22_test =X22_test.drop(['Postid'], axis = 1)


In [85]:
X22_train = X22_train.drop(['post_id'], axis = 1)
X22_test =X22_test.drop(['post_id'], axis = 1)

In [86]:
X22_train = X22_train.drop(['ind'], axis = 1)
X22_test =X22_test.drop(['ind'], axis = 1)

In [87]:
x_train = X22_train
x_test = X22_test
get_eval()

lr : precision: 0.77, recall: 0.66, f1_score: 0.68
 confusion_matrix: 
 [[144 202]
 [ 41 328]]
knn : precision: 0.61, recall: 0.61, f1_score: 0.61
 confusion_matrix: 
 [[198 148]
 [133 236]]
DecisionTree : precision: 0.76, recall: 0.73, f1_score: 0.74
 confusion_matrix: 
 [[207 139]
 [ 54 315]]
svm : precision: 0.71, recall: 0.71, f1_score: 0.71
 confusion_matrix: 
 [[234 112]
 [ 97 272]]
bayes : precision: 0.64, recall: 0.48, f1_score: 0.53
 confusion_matrix: 
 [[ 64 282]
 [ 87 282]]
xgboost : precision: 0.75, recall: 0.74, f1_score: 0.74
 confusion_matrix: 
 [[228 118]
 [ 69 300]]
GBM : precision: 0.76, recall: 0.74, f1_score: 0.74
 confusion_matrix: 
 [[214 132]
 [ 57 312]]
rf : precision: 0.64, recall: 0.61, f1_score: 0.62
 confusion_matrix: 
 [[171 175]
 [101 268]]
adaboost : precision: 0.71, recall: 0.69, f1_score: 0.69
 confusion_matrix: 
 [[198 148]
 [ 75 294]]


In [144]:
get_majority_vote()

[Voting] ............. (3 of 9) Processing DecisionTree, total=   1.5s
[Voting] ...................... (2 of 9) Processing knn, total=   1.9s
[Voting] .................... (5 of 9) Processing bayes, total=   2.3s
[Voting] .................. (6 of 9) Processing xgboost, total=  14.1s
[Voting] ....................... (8 of 9) Processing rf, total=   1.6s
[Voting] ...................... (7 of 9) Processing GBM, total=  23.7s
[Voting] ................. (9 of 9) Processing adaboost, total=  11.0s
[Voting] ....................... (1 of 9) Processing lr, total= 1.3min
[Voting] ...................... (4 of 9) Processing svm, total= 1.4min
{'0': {'precision': 0.7868852459016393, 'recall': 0.5549132947976878, 'f1-score': 0.6508474576271186, 'support': 346}, '1': {'precision': 0.673036093418259, 'recall': 0.8590785907859079, 'f1-score': 0.7547619047619049, 'support': 369}, 'accuracy': 0.7118881118881119, 'macro avg': {'precision': 0.7299606696599492, 'recall': 0.7069959427917978, 'f1-score': 0.70

In [88]:
results_for_corr_df = get_res_for_corr()
method = method + '_correlated'

get_majority_vote_correlated(results_for_corr_df)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


droping: []
droping: ['xgboost', 'GBM']
[Voting] ............. (3 of 7) Processing DecisionTree, total=   0.8s
[Voting] ...................... (2 of 7) Processing knn, total=   1.4s
[Voting] ....................... (6 of 7) Processing rf, total=   1.2s
[Voting] .................... (5 of 7) Processing bayes, total=   2.2s
[Voting] ................. (7 of 7) Processing adaboost, total=   9.8s
[Voting] ...................... (4 of 7) Processing svm, total= 1.3min
[Voting] ....................... (1 of 7) Processing lr, total= 1.3min
{'0': {'precision': 0.7736625514403292, 'recall': 0.5433526011560693, 'f1-score': 0.6383701188455008, 'support': 346}, '1': {'precision': 0.6652542372881356, 'recall': 0.8509485094850948, 'f1-score': 0.7467300832342448, 'support': 369}, 'accuracy': 0.7020979020979021, 'macro avg': {'precision': 0.7194583943642324, 'recall': 0.6971505553205821, 'f1-score': 0.6925501010398728, 'support': 715}, 'weighted avg': {'precision': 0.7177147641366097, 'recall': 0.702097

In [89]:
pd.DataFrame(summ_results)

name  precision    recall  \
0   Orig_features_no_post_comments_usr_emb_text_cl...   0.736017  0.735664   
1   Orig_features_no_post_comments_usr_emb_text_cl...   0.661473  0.636364   
2   Orig_features_no_post_comments_usr_emb_text_cl...   0.760431  0.730070   
3   Orig_features_no_post_comments_usr_emb_text_cl...   0.723856  0.721678   
4   Orig_features_no_post_comments_usr_emb_text_cl...   0.866421  0.517483   
5   Orig_features_no_post_comments_usr_emb_text_cl...   0.749019  0.738462   
6   Orig_features_no_post_comments_usr_emb_text_cl...   0.772049  0.732867   
7   Orig_features_no_post_comments_usr_emb_text_cl...   0.713255  0.713287   
8   Orig_features_no_post_comments_usr_emb_text_cl...   0.719050  0.693706   
9   Orig_features_no_post_comments_usr_emb_text_cl...   0.752450  0.746853   
10  Orig_features_no_post_comments_usr_emb_text_cl...   0.745464  0.741259   
11  Orig_features_no_post_comments_usr_emb_text_cl...   0.751736  0.748252   
12  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.667087  0.538462   
13  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.569030  0.496503   
14  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.976412  0.490909   
15  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.612588  0.555245   
16  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.866421  0.517483   
17  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.963820  0.525874   
18  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.798459  0.545455   
19  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.504754  0.499301   
20  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.862579  0.523077   
21  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.555817  0.545455   
22  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.545541  0.539860   
23  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.766581  0.660140   
24  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.608405  0.606993   
25  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.760431  0.730070   
26  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.708968  0.707692   
27  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.641895  0.483916   
28  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.749019  0.738462   
29  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.759479  0.735664   
30  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.638004  0.613986   
31  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.711032  0.688112   
32  Word2vec_for_post_cluster_based_on_word2vec_fo...   0.717715  0.702098   

          f1          confusion_matrix  
0   0.735597   [[258, 88], [101, 268]]  
1   0.641820   [[178, 168], [92, 277]]  
2   0.735030   [[207, 139], [54, 315]]  
3   0.721737   [[260, 86], [113, 256]]  
4   0.626084    [[27, 319], [26, 343]]  
5   0.740285   [[228, 118], [69, 300]]  
6   0.739126   [[202, 144], [47, 322]]  
7   0.713236  [[246, 100], [105, 264]]  
8   0.698412   [[198, 148], [71, 298]]  
9   0.744426   [[226, 120], [61, 308]]  
10  0.739197   [[227, 119], [66, 303]]  
11  0.746557   [[232, 114], [66, 303]]  
12  0.572737    [[93, 253], [77, 292]]  
13  0.513620  [[237, 109], [251, 118]]  
14  0.643930      [[343, 3], [361, 8]]  
15  0.569823  [[129, 217], [101, 268]]  
16  0.626084    [[27, 319], [26, 343]]  
17  0.667637     [[12, 334], [5, 364]]  
18  0.615863    [[59, 287], [38, 331]]  
19  0.501035  [[151, 195], [163, 206]]  
20  0.626979    [[31, 315], [26, 343]]  
21  0.499192    [[81, 265], [60, 309]]  
22  0.497677    [[84, 262], [67, 302]]  
23  0.681230   [[144, 202], [41, 328]]  
24  0.607432  [[198, 148], [133, 236]]  
25  0.735030   [[207, 139], [54, 315]]  
26  0.708019   [[234, 112], [97, 272]]  
27  0.531228    [[64, 282], [87, 282]]  
28  0.740285   [[228, 118], [69, 300]]  
29  0.739538   [[214, 132], [57, 312]]  
30  0.619508  [[171, 175], [101, 268]]  
31  0.692466   [[198, 148], [75, 294]]  
32  0.694293   [[188, 158], [55, 314]]